name: Build and Deploy
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v4

      - name: Setup | Node.js
        uses: ./.github/actions/setup-node

      - name: Setup | GitHub Pages
        id: config
        uses: actions/configure-pages@v4

      - name: Run | Build
        run: pnpm build

      - name: Post Build | Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Deploy | GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
